# Generated by Django 3.1.1 on 2024-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='text',
            field=models.TextField(null=True, verbose_name='Старт'),
        ),
    ]
