# Generated by Django 3.1.1 on 2024-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20240221_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimalDepozitQancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='MinimalDepozitQancha')),
            ],
            options={
                'db_table': 'minimal_depozit_qancha',
            },
        ),
    ]
