# Generated by Django 3.1.1 on 2024-02-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_minimaldepozitqancha'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDeposite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='OneDeposite')),
            ],
            options={
                'db_table': 'one_deposite',
            },
        ),
    ]
