# Generated by Django 3.1.1 on 2024-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Pul')),
            ],
            options={
                'db_table': 'pul',
            },
        ),
    ]
