# Generated by Django 3.1.1 on 2024-02-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_pul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharhlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Sharhlar')),
            ],
            options={
                'db_table': 'sharhlar',
            },
        ),
        migrations.CreateModel(
            name='SharhlarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d')),
                ('sharhlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.sharhlar')),
            ],
            options={
                'db_table': 'sharhlar_images',
            },
        ),
    ]
