# Generated by Django 3.1.1 on 2024-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_sharhlar_sharhlarimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litsenziya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d')),
            ],
            options={
                'db_table': 'litsenziya',
            },
        ),
    ]
